/*
 * RhubarbVRApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public interface IAdminApiSync : IApiAccessor
	{
		#region Synchronous Operations
		/// <summary>
		/// 
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>string</returns>
		string AdminEdituserPost(string uuid = default(string), string authorization = default(string));

		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>ApiResponse of string</returns>
		ApiResponse<string> AdminEdituserPostWithHttpInfo(string uuid = default(string), string authorization = default(string));
		/// <summary>
		/// 
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>List&lt;PrivateUser&gt;</returns>
		List<PrivateUser> AdminFetchprivateGet(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string));

		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>ApiResponse of List&lt;PrivateUser&gt;</returns>
		ApiResponse<List<PrivateUser>> AdminFetchprivateGetWithHttpInfo(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string));
		#endregion Synchronous Operations
	}

	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public interface IAdminApiAsync : IApiAccessor
	{
		#region Asynchronous Operations
		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of string</returns>
		System.Threading.Tasks.Task<string> AdminEdituserPostAsync(string uuid = default(string), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of ApiResponse (string)</returns>
		System.Threading.Tasks.Task<ApiResponse<string>> AdminEdituserPostWithHttpInfoAsync(string uuid = default(string), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of List&lt;PrivateUser&gt;</returns>
		System.Threading.Tasks.Task<List<PrivateUser>> AdminFetchprivateGetAsync(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>
		/// 
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of ApiResponse (List&lt;PrivateUser&gt;)</returns>
		System.Threading.Tasks.Task<ApiResponse<List<PrivateUser>>> AdminFetchprivateGetWithHttpInfoAsync(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		#endregion Asynchronous Operations
	}

	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public interface IAdminApi : IAdminApiSync, IAdminApiAsync
	{

	}

	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public partial class AdminApi : IAdminApi
	{
		private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

		/// <summary>
		/// Initializes a new instance of the <see cref="AdminApi"/> class.
		/// </summary>
		/// <returns></returns>
		public AdminApi() : this((string)null)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="AdminApi"/> class.
		/// </summary>
		/// <returns></returns>
		public AdminApi(String basePath)
		{
			this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
				Org.OpenAPITools.Client.GlobalConfiguration.Instance,
				new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
			);
			this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
			this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
			this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="AdminApi"/> class
		/// using Configuration object
		/// </summary>
		/// <param name="configuration">An instance of Configuration</param>
		/// <returns></returns>
		public AdminApi(Org.OpenAPITools.Client.Configuration configuration)
		{
			if (configuration == null)
				throw new ArgumentNullException("configuration");

			this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
				Org.OpenAPITools.Client.GlobalConfiguration.Instance,
				configuration
			);
			this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
			this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
			ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="AdminApi"/> class
		/// using a Configuration object and client instance.
		/// </summary>
		/// <param name="client">The client interface for synchronous API access.</param>
		/// <param name="asyncClient">The client interface for asynchronous API access.</param>
		/// <param name="configuration">The configuration object.</param>
		public AdminApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
		{
			if (client == null)
				throw new ArgumentNullException("client");
			if (asyncClient == null)
				throw new ArgumentNullException("asyncClient");
			if (configuration == null)
				throw new ArgumentNullException("configuration");

			this.Client = client;
			this.AsynchronousClient = asyncClient;
			this.Configuration = configuration;
			this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
		}

		/// <summary>
		/// The client for accessing this underlying API asynchronously.
		/// </summary>
		public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

		/// <summary>
		/// The client for accessing this underlying API synchronously.
		/// </summary>
		public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

		/// <summary>
		/// Gets the base path of the API client.
		/// </summary>
		/// <value>The base path</value>
		public String GetBasePath()
		{
			return this.Configuration.BasePath;
		}

		/// <summary>
		/// Gets or sets the configuration object
		/// </summary>
		/// <value>An instance of the Configuration</value>
		public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

		/// <summary>
		/// Provides a factory method hook for the creation of exceptions.
		/// </summary>
		public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
		{
			get
			{
				if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
				{
					throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
				}
				return _exceptionFactory;
			}
			set { _exceptionFactory = value; }
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>string</returns>
		public string AdminEdituserPost(string uuid = default(string), string authorization = default(string))
		{
			Org.OpenAPITools.Client.ApiResponse<string> localVarResponse = AdminEdituserPostWithHttpInfo(uuid, authorization);
			return localVarResponse.Data;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>ApiResponse of string</returns>
		public Org.OpenAPITools.Client.ApiResponse<string> AdminEdituserPostWithHttpInfo(string uuid = default(string), string authorization = default(string))
		{
			Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

			String[] _contentTypes = new String[] {
			};

			// to determine the Accept header
			String[] _accepts = new String[] {
				"text/plain",
				"application/json",
				"text/json"
			};

			var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
			if (localVarContentType != null)
				localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

			var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
			if (localVarAccept != null)
				localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

			if (uuid != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "uuid", uuid));
			}
			if (authorization != null)
			{
				localVarRequestOptions.HeaderParameters.Add("Authorization", Org.OpenAPITools.Client.ClientUtils.ParameterToString(authorization)); // header parameter
			}


			// make the HTTP request
			var localVarResponse = this.Client.Post<string>("/Admin/edituser", localVarRequestOptions, this.Configuration);

			if (this.ExceptionFactory != null)
			{
				Exception _exception = this.ExceptionFactory("AdminEdituserPost", localVarResponse);
				if (_exception != null)
					throw _exception;
			}

			return localVarResponse;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of string</returns>
		public async System.Threading.Tasks.Task<string> AdminEdituserPostAsync(string uuid = default(string), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			Org.OpenAPITools.Client.ApiResponse<string> localVarResponse = await AdminEdituserPostWithHttpInfoAsync(uuid, authorization, cancellationToken).ConfigureAwait(false);
			return localVarResponse.Data;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of ApiResponse (string)</returns>
		public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<string>> AdminEdituserPostWithHttpInfoAsync(string uuid = default(string), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{

			Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

			String[] _contentTypes = new String[] {
			};

			// to determine the Accept header
			String[] _accepts = new String[] {
				"text/plain",
				"application/json",
				"text/json"
			};


			var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
			if (localVarContentType != null)
				localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

			var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
			if (localVarAccept != null)
				localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

			if (uuid != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "uuid", uuid));
			}
			if (authorization != null)
			{
				localVarRequestOptions.HeaderParameters.Add("Authorization", Org.OpenAPITools.Client.ClientUtils.ParameterToString(authorization)); // header parameter
			}


			// make the HTTP request

			var localVarResponse = await this.AsynchronousClient.PostAsync<string>("/Admin/edituser", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

			if (this.ExceptionFactory != null)
			{
				Exception _exception = this.ExceptionFactory("AdminEdituserPost", localVarResponse);
				if (_exception != null)
					throw _exception;
			}

			return localVarResponse;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>List&lt;PrivateUser&gt;</returns>
		public List<PrivateUser> AdminFetchprivateGet(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string))
		{
			Org.OpenAPITools.Client.ApiResponse<List<PrivateUser>> localVarResponse = AdminFetchprivateGetWithHttpInfo(uuid, username, identifier, matchcase, authorization);
			return localVarResponse.Data;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <returns>ApiResponse of List&lt;PrivateUser&gt;</returns>
		public Org.OpenAPITools.Client.ApiResponse<List<PrivateUser>> AdminFetchprivateGetWithHttpInfo(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string))
		{
			Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

			String[] _contentTypes = new String[] {
			};

			// to determine the Accept header
			String[] _accepts = new String[] {
				"text/plain",
				"application/json",
				"text/json"
			};

			var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
			if (localVarContentType != null)
				localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

			var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
			if (localVarAccept != null)
				localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

			if (uuid != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "uuid", uuid));
			}
			if (username != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "username", username));
			}
			if (identifier != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "identifier", identifier));
			}
			if (matchcase != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "matchcase", matchcase));
			}
			if (authorization != null)
			{
				localVarRequestOptions.HeaderParameters.Add("Authorization", Org.OpenAPITools.Client.ClientUtils.ParameterToString(authorization)); // header parameter
			}


			// make the HTTP request
			var localVarResponse = this.Client.Get<List<PrivateUser>>("/Admin/fetchprivate", localVarRequestOptions, this.Configuration);

			if (this.ExceptionFactory != null)
			{
				Exception _exception = this.ExceptionFactory("AdminFetchprivateGet", localVarResponse);
				if (_exception != null)
					throw _exception;
			}

			return localVarResponse;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of List&lt;PrivateUser&gt;</returns>
		public async System.Threading.Tasks.Task<List<PrivateUser>> AdminFetchprivateGetAsync(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			Org.OpenAPITools.Client.ApiResponse<List<PrivateUser>> localVarResponse = await AdminFetchprivateGetWithHttpInfoAsync(uuid, username, identifier, matchcase, authorization, cancellationToken).ConfigureAwait(false);
			return localVarResponse.Data;
		}

		/// <summary>
		///  
		/// </summary>
		/// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="uuid"> (optional)</param>
		/// <param name="username"> (optional)</param>
		/// <param name="identifier"> (optional)</param>
		/// <param name="matchcase"> (optional)</param>
		/// <param name="authorization">For Authenticating the user (optional)</param>
		/// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
		/// <returns>Task of ApiResponse (List&lt;PrivateUser&gt;)</returns>
		public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<PrivateUser>>> AdminFetchprivateGetWithHttpInfoAsync(string uuid = default(string), string username = default(string), int? identifier = default(int?), bool? matchcase = default(bool?), string authorization = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{

			Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

			String[] _contentTypes = new String[] {
			};

			// to determine the Accept header
			String[] _accepts = new String[] {
				"text/plain",
				"application/json",
				"text/json"
			};


			var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
			if (localVarContentType != null)
				localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

			var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
			if (localVarAccept != null)
				localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

			if (uuid != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "uuid", uuid));
			}
			if (username != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "username", username));
			}
			if (identifier != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "identifier", identifier));
			}
			if (matchcase != null)
			{
				localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "matchcase", matchcase));
			}
			if (authorization != null)
			{
				localVarRequestOptions.HeaderParameters.Add("Authorization", Org.OpenAPITools.Client.ClientUtils.ParameterToString(authorization)); // header parameter
			}


			// make the HTTP request

			var localVarResponse = await this.AsynchronousClient.GetAsync<List<PrivateUser>>("/Admin/fetchprivate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

			if (this.ExceptionFactory != null)
			{
				Exception _exception = this.ExceptionFactory("AdminFetchprivateGet", localVarResponse);
				if (_exception != null)
					throw _exception;
			}

			return localVarResponse;
		}

	}
}
